# Generated by Django 5.0.9 on 2024-11-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'sexo',
                'verbose_name_plural': 'sexos',
            },
        ),
    ]
