# Generated by Django 5.0.9 on 2024-11-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sexo',
            table='sexo',
        ),
    ]
