# Generated by Django 5.0.9 on 2024-12-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexo', '0002_alter_sexo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sexo',
            options={'ordering': ['id_sexo'], 'verbose_name': 'sexo', 'verbose_name_plural': 'sexos'},
        ),
    ]
