# Generated by Django 5.0.9 on 2024-11-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_proveedor', '0002_alter_tipoproveedor_nombre_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproveedor',
            options={'ordering': ['id_tipo_proveedor'], 'verbose_name': 'Tipo de Proveedor', 'verbose_name_plural': 'Tipos de Proveedores'},
        ),
    ]
