# Generated by Django 5.0.9 on 2024-11-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_proveedor', '0003_alter_tipoproveedor_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoproveedor',
            table='tipo_proveedor',
        ),
    ]
