# Generated by Django 5.0.9 on 2024-11-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'metodo_pago',
                'verbose_name_plural': 'metodos_pago',
            },
        ),
    ]
