# Generated by Django 5.0.9 on 2024-11-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplares', '0003_ejemplares_precio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ejemplares',
            table='ejemplares',
        ),
    ]
