# Generated by Django 5.0.9 on 2024-12-02 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplares', '0004_alter_ejemplares_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplares',
            name='descripcion',
            field=models.CharField(default='', max_length=2555),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ejemplares',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
