# Generated by Django 5.0.9 on 2024-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplares', '0005_ejemplares_descripcion_ejemplares_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplares',
            name='imagen',
            field=models.ImageField(upload_to='static/images/ejemplares'),
        ),
    ]
