# Generated by Django 5.0.9 on 2024-12-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplares', '0006_alter_ejemplares_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplares',
            name='imagen',
            field=models.ImageField(upload_to='images/ejemplares'),
        ),
    ]
