# Generated by Django 5.0.9 on 2024-11-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('tipo_suministro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suministros',
            fields=[
                ('id_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_suministro', models.CharField(max_length=255)),
                ('traido_el', models.DateField(auto_now_add=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
                ('id_tipo_suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_suministro.tiposuministro')),
            ],
        ),
    ]
