# Generated by Django 5.0.9 on 2024-11-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suministros',
            options={'ordering': ['id_suministro'], 'verbose_name': 'Suministro', 'verbose_name_plural': 'Suministros'},
        ),
    ]
