# Generated by Django 5.0.9 on 2024-11-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0003_suministros_stock'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suministros',
            table='suministros',
        ),
    ]
