# Generated by Django 5.0.9 on 2024-11-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSuministro',
            fields=[
                ('id_tipo_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_suministro', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Suministro',
                'verbose_name_plural': 'Tipos de Suministros',
                'ordering': ['id_tipo_suministro'],
            },
        ),
    ]
