# Generated by Django 5.0.9 on 2024-11-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_suministro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiposuministro',
            table='tipo_suministro',
        ),
    ]
