# Generated by Django 5.0.9 on 2024-12-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_ventas_options_alter_ventas_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['fecha'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
