# Generated by Django 5.0.9 on 2024-11-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_proveedor', '0003_alter_tipoproveedor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('id_tipo_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_proveedor.tipoproveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
