# Generated by Django 5.0.9 on 2024-10-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id_tipo_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Empleado',
                'verbose_name_plural': 'Tipos de Empleados',
                'db_table': 'tipo_empleado',
            },
        ),
    ]
