# Generated by Django 5.0.9 on 2024-11-22 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree_ejemplar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigreeejemplar',
            name='porcentaje_pureza',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
