# Generated by Django 5.0.9 on 2024-11-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree_ejemplar', '0002_alter_pedigreeejemplar_porcentaje_pureza'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedigreeejemplar',
            table='pedigree_ejemplar',
        ),
    ]
