# Generated by Django 5.0.9 on 2024-12-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_account_can_write'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='can_write',
            new_name='escritura',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_staff',
            new_name='lectura',
        ),
    ]
