# Generated by Django 5.0.10 on 2024-12-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_rename_can_write_account_escritura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='escritura',
            new_name='is_criador',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lectura',
            new_name='is_cuidador',
        ),
        migrations.AddField(
            model_name='account',
            name='is_veterinario',
            field=models.BooleanField(default=False),
        ),
    ]
