# Generated by Django 5.0.10 on 2024-12-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_rename_escritura_account_is_criador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
