# Generated by Django 5.0.9 on 2024-11-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
