# Generated by Django 5.0.9 on 2024-11-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_correo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
    ]
