# Generated by Django 5.0.9 on 2024-11-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_color', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
            },
        ),
    ]
