# Generated by Django 5.0.9 on 2024-11-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['id_color'], 'verbose_name': 'color', 'verbose_name_plural': 'colores'},
        ),
    ]
