# Generated by Django 5.0.9 on 2024-11-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_alter_color_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='color',
            table='color',
        ),
    ]
