# Generated by Django 5.0.9 on 2024-11-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Razas',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_raza', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='images/razas')),
            ],
            options={
                'verbose_name': 'raza',
                'verbose_name_plural': 'razas',
            },
        ),
    ]
