# Generated by Django 5.0.9 on 2024-11-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razas',
            name='imagen',
            field=models.ImageField(upload_to='static/images/razas'),
        ),
    ]
